Added common linters
ros-perception/laser_geometry pull request #96
Opened 2024-07-12 12:49 UTC by ahcorde

2024-07-12 13:05 UTC, clalancette requested changes

2024-07-12 13:05 UTC, clalancette commented on CONTRIBUTING.md
> +[license](https://opensource.org/licenses/BSD-3-Clause).
This is actually incorrect (there is no such thing as the BSD license 2.0; I don't know what I was thinking when I added that to ament_lint all those years ago).  This should be:

```suggestion
Any contribution that you make to this repository will
be under the 3-Clause BSD License, as dictated by that
[license](https://opensource.org/licenses/BSD-3-Clause).
```

2024-07-12 13:05 UTC, clalancette commented on src/laser_geometry/__init__.py
> +# Redistribution and use in source and binary forms, with or without
This should probably be:

```suggestion
# Copyright (c) 2014, Enrique Fernandez
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
```

(it came in with commit d4785e879a06f2dc7c66cae58c742021677e0966 that added `laser_geometry.py` below)

2024-07-12 13:05 UTC, clalancette commented on src/laser_geometry/laser_geometry.py
> +# Redistribution and use in source and binary forms, with or without
```suggestion

# Redistribution and use in source and binary forms, with or without
```

2024-07-12 13:05 UTC, clalancette commented on test/projection_test.py
>  #!/usr/bin/env python3
```suggestion
```

2024-07-12 13:05 UTC, clalancette commented on test/projection_test.py
> +# Redistribution and use in source and binary forms, with or without
This should likely be:

```suggestion
# Copyright (c) 2014, Enrique Fernandez
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
```

(it came in with 0ed1dafb145039ff58cc6b141893713dc918d867, around the same time as the rest)

2024-07-24 21:10 UTC, ahcorde commented
friendly ping @clalancette

2024-07-25 11:30 UTC, clalancette requested changes
Two more small changes, then I think this will be good to go.

2024-07-25 11:30 UTC, clalancette commented on package.xml
> +  <url type="website">http://ros.org/wiki/laser_geometry</url>
Sorry, I missed this earlier.  We shouldn't point to the wiki anymore, but instead:

```suggestion
  <url type="website">http://github.com/ros-perception/laser_geometry</url>
```

2024-07-25 11:30 UTC, clalancette commented on src/laser_geometry/laser_geometry.py
We shouldn't give the executable bit to this file.  That is, we should leave the permissions as 100644.

2024-08-19 12:35 UTC, ahcorde commented on src/laser_geometry/laser_geometry.py
https://github.com/ros-perception/laser_geometry/pull/96/commits/c209925257d55c1f744cde70b185ea163c5d6fea

2024-08-19 13:14 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21668)](http://ci.ros2.org/job/ci_linux/21668/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15952)](http://ci.ros2.org/job/ci_linux-aarch64/15952/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1171)](http://ci.ros2.org/job/ci_linux-rhel/1171/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22383)](http://ci.ros2.org/job/ci_windows/22383/)

2024-08-19 14:29 UTC, clalancette approved these changes

2024-08-19 14:32 UTC, merged